@echo off
echo Stopping any existing Node.js processes...
taskkill /f /im node.exe >nul 2>&1
echo Starting Cryptexa server...
start npm start
echo Waiting for server to start...
timeout /t 3 /nobreak >nul
echo Opening localhost:3000 in incognito mode...
start "" "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --incognito http://localhost:3000/dispo3