/**
 * Server request validation tests using production validators.
 */

import { describe, it, expect } from 'vitest';
import { normalizeSiteKey, validateEncryptedContent, validateHashToken } from '../../src/server/validation';

const validEncryptedContent = `${'a'.repeat(32)}:${'b'.repeat(24)}:${'c'.repeat(32)}`;

describe('normalizeSiteKey', () => {
    it('accepts safe workspace identifiers', () => {
        expect(normalizeSiteKey('workspace-1').ok).toBe(true);
        expect(normalizeSiteKey('team.notes_2026~prod').ok).toBe(true);
        expect(normalizeSiteKey(12345).ok).toBe(true);
    });

    it('rejects missing, reserved, malformed, or oversized site keys', () => {
        expect(normalizeSiteKey('').ok).toBe(false);
        expect(normalizeSiteKey('api').ok).toBe(false);
        expect(normalizeSiteKey('with space').ok).toBe(false);
        expect(normalizeSiteKey('../secret').ok).toBe(false);
        expect(normalizeSiteKey('a'.repeat(129)).ok).toBe(false);
        expect(normalizeSiteKey({}).ok).toBe(false);
    });
});

describe('validateHashToken', () => {
    it('accepts empty and safe hash tokens', () => {
        expect(validateHashToken('', 'initHashContent').ok).toBe(true);
        expect(validateHashToken('abc123._:~-', 'currentHashContent').ok).toBe(true);
    });

    it('rejects non-strings, unsafe characters, and oversized tokens', () => {
        expect(validateHashToken(null, 'initHashContent').ok).toBe(false);
        expect(validateHashToken('abc def', 'initHashContent').ok).toBe(false);
        expect(validateHashToken('a'.repeat(513), 'initHashContent').ok).toBe(false);
    });
});

describe('validateEncryptedContent', () => {
    it('accepts salt:iv:cipher payloads generated by the client', () => {
        const result = validateEncryptedContent(validEncryptedContent);
        expect(result.ok).toBe(true);
        if (result.ok) {
            expect(result.value).toBe(validEncryptedContent);
        }
    });

    it('rejects malformed payloads', () => {
        expect(validateEncryptedContent(null).ok).toBe(false);
        expect(validateEncryptedContent('abc').ok).toBe(false);
        expect(validateEncryptedContent('abc:def').ok).toBe(false);
        expect(validateEncryptedContent('a:b:c:d').ok).toBe(false);
        expect(validateEncryptedContent('::').ok).toBe(false);
    });

    it('rejects non-hex or incorrectly sized components', () => {
        expect(validateEncryptedContent(`${'g'.repeat(32)}:${'b'.repeat(24)}:${'c'.repeat(32)}`).ok).toBe(false);
        expect(validateEncryptedContent(`${'a'.repeat(30)}:${'b'.repeat(24)}:${'c'.repeat(32)}`).ok).toBe(false);
        expect(validateEncryptedContent(`${'a'.repeat(32)}:${'b'.repeat(22)}:${'c'.repeat(32)}`).ok).toBe(false);
        expect(validateEncryptedContent(`${'a'.repeat(32)}:${'b'.repeat(24)}:${'c'.repeat(30)}`).ok).toBe(false);
    });
});
